# Select docker provider by default
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(2) do |config|

  config.vm.define "01_bare_server" do |a|
    a.vm.provider "docker" do |docker|

      # Relative path to build docker image
      docker.build_dir = "."

      # Tag compiled docker container
      docker.build_args = ["-t=01_bare_server"]

      # Map ports: array of "host:guest" pairs from container to docker host OS
      docker.ports = ["44000:3000"]

      docker.name = "01_bare_server"
      docker.remains_running = true

      # Here we define custom VM for hosting docker, not default boot2docker
      if RUBY_PLATFORM !~ /linux/i
        docker.vagrant_machine = "01_bare_dockerhost"
        docker.vagrant_vagrantfile = "./VagrantfileForDocker"
      end
    end
  end

end
